version: '3'

services:
  app:
    image: gveloso/calculator
    restart: always
    ports:
      - "8080:8080"

  mock-server:
    image: gveloso/mock-server
    restart: always
    ports:
      - "8081:8081"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"